[package]
name = "app-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["std", "derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
schemars = "0.8"
regex = "1"
lazy_static = "1.4"
literal = "0.2"
log = "0.4"
env_logger = "0.9"
